export const PLAN_LIST_REPOSITORY = Symbol("PLAN_LIST_REPOSITORY");
export const PLAN_CREATOR_REPOSITORY = Symbol("PLAN_CREATOR_REPOSITORY");
export const USER_CREATOR_REPOSITORY = Symbol("USER_CREATOR_REPOSITORY");
export const USER_AUTHENTICATOR_REPOSITORY = Symbol("USER_AUTHENTICATOR_REPOSITORY");
