@startuml
 
state INITIAL
state PLANCREATED as "CREATED PLAN"
state JOINEDPLAN as "JOINED PLAN"
state ATTENDPLAN as "ATTENDED A PLAN"
state RATEDPLAN as "RATE A PLAN"
state RATEDOWNER as "RATE A PLAN OWNER"
state RATEATENDEE as "RATE ATENDEES"

[*] --> INITIAL
INITIAL --> PLANCREATED : User creates a plan
INITIAL --> JOINEDPLAN : User joins a plan
PLANCREATED --> ATTENDPLAN : User attends a plan
JOINEDPLAN --> ATTENDPLAN : User attends a plan
ATTENDPLAN --> RATEDOWNER : User rates the plan owner
ATTENDPLAN --> RATEDPLAN : User rates the plan
ATTENDPLAN --> RATEATENDEE : User rates atendees
RATEDPLAN --> [*]
RATEDPLAN --> [*]
RATEATENDEE --> [*]

@enduml